### ISSUE TITLE
Simpler assert in readme example code

### ISSUE THREAD

**Issue by dtolnay** [garrensmith/rustybench#2]
We added square bracket indexing in serde_json 0.9.0 and PartialEq implementations in serde_json 0.9.3 so this assertion from the readme:

```rust
assert_eq!(doc.get("class").unwrap().as_str().unwrap(), "mammal");
```

can now be written more simply as:

```rust
assert_eq!(doc["class"], "mammal");
```

**Comment by garrensmith** [comment]
This is awesome. Thank you for the help. I've updated the readme, code and docs.
